version: 0.0
os: linux

files:
  - source: /www.alexstancu.ro
    destination: /var/www/www.alexstancu.ro

permissions:
  - object: /var/www/www.alexstancu.ro
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 664
    type:
      - file

  - object: /var/www/www.alexstancu.ro
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 775
    type:
      - directory

hooks:
  ApplicationStop:
    - location: codedeploy/deregister-from-elb.sh
    - location: codedeploy/stop-app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy/start-app.sh
      timeout: 300
      runas: root
    - location: codedeploy/register-with-elb.sh
      timeout: 300
  ValidateService:
    - location: codedeploy/validate.sh
      timeout: 30
